//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AppModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaciaEntities : DbContext
    {
        public FarmaciaEntities()
            : base("name=FarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblCliente> TblCliente { get; set; }
        public DbSet<TblCuentas> TblCuentas { get; set; }
        public DbSet<TblFabricante> TblFabricante { get; set; }
        public DbSet<TblFactura> TblFactura { get; set; }
        public DbSet<TblMedicamentos> TblMedicamentos { get; set; }
        public DbSet<TblVendedor> TblVendedor { get; set; }
    }
}
