//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuentas
    {
        public int IdCuenta { get; set; }
        public int NumFact { get; set; }
        public string NomVen { get; set; }
        public string NomMed { get; set; }
        public int CantMed { get; set; }
        public int PrecioMed { get; set; }
        public int TotalCuenta { get; set; }
    }
}
