//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactura
    {
        public int FacId { get; set; }
        public string NomVen { get; set; }
        public string NomCliente { get; set; }
        public string ApeCliente { get; set; }
        public string TelCliente { get; set; }
        public string CedCliente { get; set; }
        public System.DateTime FactFecha { get; set; }
        public int FactCantidad { get; set; }
    }
}
