//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFabricante
    {
        public int FabId { get; set; }
        public string NomFab { get; set; }
        public string DirFab { get; set; }
        public string CedulaFab { get; set; }
        public string TelFab { get; set; }
        public System.DateTime FechaInFab { get; set; }
    }
}
