//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVendedor
    {
        public int IdVen { get; set; }
        public string NomVen { get; set; }
        public System.DateTime FechaNacVen { get; set; }
        public string TelVen { get; set; }
        public string DirVen { get; set; }
        public string CedulaVen { get; set; }
        public string GenVen { get; set; }
        public string ContraVen { get; set; }
        public int SueldoVen { get; set; }
    }
}
